# Generated by Django 6.0.2 on 2026-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
