# Generated by Django 6.0.2 on 2026-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_account_alter_customer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=30),
        ),
    ]
